version: "3"

services:
  influxdb:
    container_name: influxdb
    restart: unless-stopped
    image: influxdb:2.0.4
    platform: arm64
    ports:
      - "8086:8086"
    volumes:
      - "$PWD/data-volume:/var/lib/influxdb2"

